name: Test firewall ds/rs

on:
  push:
    branches:
      - master
    paths-ignore:
      - "website/**"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_firewall**"
      - "gridscale/firewall-utils/**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"

jobs:
  build:
    name: Firewall AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: https://api.gridscale.cloud
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccdataSourceGridscaleFirewall_basic
        run: for i in $(seq 1 3); do make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleFirewall_basic' && s=0 && break || s=$? && sleep 10; done; (exit $s)

      - name: Run TestAccResourceGridscaleFirewall_Basic
        run: for i in $(seq 1 3); do make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleFirewall_Basic' && s=0 && break || s=$? && sleep 10; done; (exit $s)
