name: Test IPv4/IPv6 ds/rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/ipv4_ipv6.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_ipv**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/ipv4_ipv6.yml"

jobs:
  build:
    name: IPv4/IPv6 AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v5
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run TestAccdataSourceGridscaleIPv4_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleIPv4_basic'

      - name: Run TestAccdataSourceGridscaleIPv6_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleIPv6_basic'

      - name: Run TestAccResourceGridscaleIpv4_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleIpv4_Basic'

      - name: Run TestAccResourceGridscaleIpv6_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleIpv6_Basic'
