name: Test k8s rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/k8s.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_k8s**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/k8s.yml"

jobs:
  build:
    name: GS k8s AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccResourceGridscaleK8s_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleK8s_Basic'
