name: Test Redis store/cache rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/redis.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_redis**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/redis.yml"

jobs:
  build:
    name: GS Redis store/cache AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: https://api.gridscale.cloud
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run TestAccResourceGridscaleRedisStore_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleRedisStore_Basic'

      - name: Run TestAccResourceGridscaleRedisCache_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleRedisCache_Basic'
