name: Test snapshot/snapshot schedule ds/rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/snapshot.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_snapshot**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/snapshot.yml"

jobs:
  build:
    name: Snapshot/Snapshot schedule AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v5
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run TestAccdataSourceGridscaleSnapshot_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleSnapshot_basic'

      - name: Run TestAccdataSourceGridscaleSnapshotSchedule_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleSnapshotSchedule_basic'

      - name: Run TestAccResourceGridscaleSnapshot_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleSnapshot_Basic'

      - name: Run TestAccResourceGridscaleSnapshotSchedule_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleSnapshotSchedule_Basic'
