name: Test Storage ds/rs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/storage.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**gridscale_storage**"
      - "gridscale/error-handler/**"
      - "gridscale/common.go"
      - "gridscale/config.go"
      - "gridscale/provider.go"
      - "gridscale/provider_test.go"
      - ".github/workflows/storage.yml"

jobs:
  build:
    name: Storage AccTest
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GRIDSCALE_UUID: ${{ secrets.CI_USER_UUID }}
      GRIDSCALE_TOKEN: ${{ secrets.CI_API_TOKEN }}
      GRIDSCALE_URL: ${{ secrets.CI_API_URL }}
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run TestAccdataSourceGridscaleStorage_basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccdataSourceGridscaleStorage_basic'

      - name: Run TestAccResourceGridscaleStorage_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleStorage_Basic'

      - name: Run TestAccResourceGridscaleStorageClone_Basic
        run: make testacc TEST=./gridscale TESTARGS='-run=TestAccResourceGridscaleStorageClone_Basic'
